version: '3'
services:
  httpd:
    build:
      context: ./httpd
      dockerfile: Dockerfile
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    networks:
      - public
    volumes:
      - $PWD/config/psamaui/settings.json:/usr/local/apache2/htdocs/psamaui/picSure/settings.json
      - $PWD/config/psamaui/settings.json:/usr/local/apache2/htdocs/psamaui/settings/settings.json
      - $PWD/config/picsureui/settings.json:/usr/local/apache2/htdocs/picsureui/settings/settings.json
    #   - ./target/pic-sure-ui:/usr/local/apache2/htdocs
    #   - ./src/main/javascript/overrides:/usr/local/apache2/htdocs/overrides
    #   - ./src/main/resources:/usr/local/apache2/htdocs/settings

  ## PIC-SURE API Stack ##
  # IRCT
  irct:
    image: dbmi/irct:${irct_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
    depends_on:
      - httpd
      - i2b2-wildfly
    env_file:
      - ${ENV_FILE}
    volumes:
      - $PWD/config/irct/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml
    restart: always
    networks:
      - public
    expose:
      - 8080

# PIC-SURE i2b2-wildfly resource
  i2b2-wildfly:
    image: dbmi/i2b2-wildfly:${i2b2_wildfly_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
    env_file:
      - ${ENV_FILE}
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true
    restart: always
    networks:
      - public
    expose:
      - 9090

## PIC-SURE API Stack ##
  # PICSURE-2.0
  picsure2:
    image: dbmi/picsure2:${picsure2_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
    depends_on:
      - httpd
    env_file:
      - ${ENV_FILE}
    volumes:
      - $PWD/config/picsure2/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml
    restart: always
    expose:
      - 8080
    command: --server-config=standalone.xml
    networks:
      - public

  psama:
    image: dbmi/pic-sure-auth-services:${psama_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
    env_file:
      - ${ENV_FILE}
    volumes:
      - $PWD/config/psama/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml
    expose:
      - 8080
    networks:
      - public

  # i2b2transmart database. For testing purposes
  db:
    image: dbmi/i2b2transmart-db:${db_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
    restart: always
    networks:
      - public
    expose:
      - 1521
    ports:
      - ${DOCKER_DB_PORT:-1521}:1521

  # Docker image of MySQL DB for picsure and irct services. Remove if using RDS instead
  # MySQL DB
  mysqldb:
    #image: dbmi/irct-db:${irctdb_version}
    build:
      context: mysql-db
      dockerfile: Dockerfile
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
    env_file:
      - ${ENV_FILE}
    restart: always
    command: --datadir=/mysql/data
    networks:
      - public
    expose:
      - 3306
    # PIC-SURE database exposed port
    ports:
      - ${DOCKER_MYSQL_DB_PORT:-3306}:3306
    volumes:
      - mysql-data:/mysql/data

volumes:
  mysql-data:

networks:
  public:
